var regular={       
                    var1:{re:/id="box_x0020_box-F([0-9]{1})-B([0-9]{1})"/g,                                   change:'class="box box-F$1-B$2"'},
                    var2:{re:/<g id="hiter_x0020_hiter-F([0-9]{1,})-H([0-9]{1,})">/g,                         change:'<g class="hiter hiter-F$1-H$2">'},
                    var3:{re:/id="F([0-9]{1,})-H([0-9]{1,})-select" class="/g,                                change:'class="F$1-H$2-select '},
                    var4:{re:/id="F([0-9]{1,})-H([0-9]{1,})[_]{0,}[0-9]{0,}" class="/g,                       change:'class="F$1-H$2 '},
                    var5:{re:/id="F([0-9]{1,})-H([0-9]{1,})-manual[_]{0,}[0-9]{0,}" class="/g,                change:'class="F$1-H$2-manual '},
                    var6:{re:/<g id="icon_x0020_attention-F([0-9]{1,})-H([0-9]{1,})">/g,                      change:'<g class="icon attention-F$1-H$2">'},
                    var7:{re:/<g id="hiter_x0020_hiter-F([0-9]{1,})-B([0-9]{1,})-H([0-9]{1,})">/g,            change:'<g class="hiter hiter-F$1-B$2-H$3">'},
                    var8:{re:/id="F([0-9]{1,})-B([0-9]{1,})-H([0-9]{1,})-select" class="/g,                   change:'class="F$1-B$2-H$3-select '},
                    var9:{re:/id="F([0-9]{1,})-B([0-9]{1,})-H([0-9]{1,})[_]{0,}[0-9]{0,}" class="/g,          change:'class="F$1-B$2-H$3 '},
                    var10:{re:/id="F([0-9]{1,})-B([0-9]{1,})-H([0-9]{1,})-manual[_]{0,}[0-9]{0,}" class="/g,  change:'class="F$1-B$2-H$3-manual '},
                    var11:{re:/<g id="icon_x0020_attention-F([0-9]{1,})-B([0-9]{1,})-H([0-9]{1,})">/g,        change:'<g class="icon attention-F$1-B$2-H$3">'},
                    var12:{re:/<g id="F([0-9]{1,})-B([0-9]{1,})-D-([a-z]{1,6})">/g,                           change:'<g class="F$1-B$2-D-$3">'},
                    var13:{re:/id="F([0-9]{1,})-B([0-9]{1,})-T([0-9]{1,})([-]{0,1})([text]{0,4})" class="/g,  change:'class="F$1-B$2-T$3$4$5 '},
                    var14:{re:/id="F([0-9]{1,})-B([0-9]{1,})-([aA-zZ]{6,11})" class="/g,                      change:'class="F$1-B$2-$3 '},
                    var15:{re:/<g id="gate_x0020_gate-F([0-9]{1,})-B([0-9]{1,})-G([0-9]{1,})">/g,             change:'<g class="gate gate-F$1-B$2-G$3">'},
                    var16:{re:/id="F([0-9]{1,})-B([0-9]{1,})-G([0-9]{1,})-select" class="/g,             change:'class="F$1-B$2-G$3-select '},
                    var17:{re:/id="F([0-9]{1,})-B([0-9]{1,})-G([0-9]{1,})[_]{0,}[0-9]{0,}" class="/g,         change:'class="F$1-B$2-G$3 '},
                    var18:{re:/<g id="icon_x0020_attention-F([0-9]{1,})-B([0-9]{1,})-G([0-9]{1,})">/g,        change:'<g class="icon attention-F$1-B$2-G$3">'},
                    var19:{re:/<g id="icon_x0020_attention-F([0-9]{1,})-B([0-9]{1,})-C([0-9]{1,})">/g,        change:'<g class="icon attention-F$1-B$2-C$3">'},
                    var20:{re:/<g id="icon_x0020_remont-F([0-9]{1,})-B([0-9]{1,})-C([0-9]{1,})">/g,           change:'<g class="icon remont-F$1-B$2-C$3">'},
                    var21:{re:/<g id="cooler_x0020_coller-F([0-9]{1,})-B([0-9]{1,})-C([0-9]{1,})">/g,         change:'<g class="cooler cooler-F$1-B$2-C$3">'},
                    var22:{re:/id="F([0-9]{1,})-B([0-9]{1,})-C([0-9]{1,})([-]{0,})([A-Z]{0,1})([0-9]{0,})([-]{0,})([A-Z]{0,8})([_]{0,})([0-9]{0,})" class="/g, change:'class="F$1-B$2-C$3$4$5$6$7$8 '},
                    var23:{re:/id="F([0-9]{1,})-B([0-9]{1,})-C([0-9]{1,})" class="/g,                         change:'class="F$1-B$2-C$3 '},
                    var24:{re:/id="F([0-9]{1,})-B([0-9]{1,})-C([0-9]{1,})-([A-Z]{1})([0-9]{0,})" class="/g,   change:'class="F$1-B$2-C$3-$4$5 '},
                    var25:{re:/id="F([0-9]{1,})-B([0-9]{1,})-C([0-9]{1,})-([A-Z]{1})([0-9]{0,})-([a-z]{4,8})[_]{0,}[0-9]{0,}" class="/g, change:'class="F$1-B$2-C$3-$4$5-$6 '},
                    var26:{re:/id="F([0-9]{1,})-B([0-9]{1,})-C([0-9]{1,})-([a-z]{4,8})" class="/g,            change:'class="F$1-B$2-C$3-$4 '},
                    var27:{re:/id="temperature([0-9]{1,})status[_]{0,}([0-9]{0,})" class="/g,                 change:'class="temperature$1status '},
                    var28:{re:/id="human[_]{0,}([0-9]{0,})" class="/g,                                        change:'class="human '},
                    var29:{re:/id="infoText[_]{0,}([0-9]{0,})" class="/g,                                     change:'class="infoText '},
                    var30:{re:/id="infoStatus[_]{0,}([0-9]{0,})" class="/g,                                   change:'class="infoStatus '},
                    var31:{re:/<g id="Слой_x0020_1">/g,                                                       change:'<g id="Слой_x0020_1"><title class="title_very_dificult">:-)</title>'},
                    var32:{re:/id="temperature([0-9]{1,})[_]{0,}([0-9]{0,})" class="/g,                       change:'class="temperature$1 '},
                    var33:{re:/id="F([0-9]{1,})-B([0-9]{1,})[_]{0,}[0-9]{0,}" class="/g,                       change:'class="F$1-B$2 '}, 
                };
exports.regular=regular;